# Generated by Django 4.1.8 on 2023-05-08 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_store.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                ("patronymic", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house", models.IntegerField(blank=True, null=True)),
                ("corps", models.CharField(blank=True, max_length=255, null=True)),
                ("apartment", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True, unique=True)),
                ("date_of_birth", models.DateField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", main_store.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("number", models.IntegerField()),
                ("size", models.FloatField()),
                ("price", models.IntegerField()),
                ("description", models.TextField(max_length=100000)),
                ("category", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(blank=True, default="Active", max_length=255, null=True)),
                ("sum_of_order", models.FloatField()),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("discount_percentage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=10000)),
                ("stars", models.FloatField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="main_store.items")),
            ],
        ),
        migrations.CreateModel(
            name="Pictures",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("picture", models.CharField(max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pictures", to="main_store.items"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrederData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main_store.items")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main_store.orders")),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_store.promocode",
            ),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main_store.items")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", models.CharField(max_length=255)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main_store.items")),
            ],
        ),
        migrations.CreateModel(
            name="Buket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(default=0)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main_store.items")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="likes",
            constraint=models.UniqueConstraint(fields=("user", "item"), name="user_item_buket"),
        ),
        migrations.AddConstraint(
            model_name="buket",
            constraint=models.UniqueConstraint(fields=("user", "item"), name="user_item"),
        ),
    ]
