# Generated by Django 4.1.7 on 2023-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
