# Generated by Django 4.1.8 on 2023-05-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_store.promocode",
            ),
        ),
    ]
