# Generated by Django 4.1.8 on 2023-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0002_alter_pictures_picture_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Администратор"), ("staff", "Сотрудник"), ("user", "Пользователь")],
                default="user",
                max_length=15,
            ),
        ),
    ]
