# Generated by Django 4.1.2 on 2023-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="category",
            field=models.CharField(max_length=25),
        ),
    ]
