# Generated by Django 4.1.2 on 2023-04-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0003_alter_items_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pictures",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pictures", to="main_store.items"
            ),
        ),
    ]
