# Generated by Django 4.1.8 on 2023-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0005_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
