# Generated by Django 4.1.8 on 2023-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0007_remove_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
