# Generated by Django 4.1.8 on 2023-05-01 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_store", "0008_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
